# @generated - Extended BarBuilder declaration with custom field support
# This file is auto-generated by build.py

from libc.stdint cimport uint8_t, uint64_t

from nautilus_trader.model.data cimport Bar, BarType
from nautilus_trader.model.objects cimport Price, Quantity


cdef class BarBuilder:
    cdef BarType _bar_type

    cdef readonly uint8_t price_precision
    cdef readonly uint8_t size_precision
    cdef readonly bint initialized
    cdef readonly uint64_t ts_last
    cdef readonly int count

    cdef bint _partial_set
    cdef Price _last_close
    cdef Price _open
    cdef Price _high
    cdef Price _low
    cdef Price _close
    cdef Quantity volume

    cdef Logger _log 

    cdef double _ext_amt_accum
    cdef double _ext_amt_multiplier


    cpdef void set_partial(self, Bar partial_bar)
    cpdef void update(self, Price price, Quantity size, uint64_t ts_event)
    cpdef void update_bar(self, Bar bar, Quantity volume, uint64_t ts_init)
    cpdef void reset(self)
    cpdef Bar build_now(self)
    cpdef Bar build(self, uint64_t ts_event, uint64_t ts_init)
