# @generated - Extended BarBuilder with custom field support
# This file is auto-generated by build.py

from decimal import Decimal
from typing import Callable

from libc.stdint cimport uint64_t, uint8_t

from nautilus_trader.core.correctness cimport Condition
from nautilus_trader.model.data cimport Bar, BarType
from nautilus_trader.model.instruments.base cimport Instrument
from nautilus_trader.model.objects cimport Price, Quantity


cdef class BarBuilder:
    """
    Extended BarBuilder with custom field accumulation support.
    """

    def __init__(
        self,
        Instrument instrument not None,
        BarType bar_type not None,
    ) -> None:
        Condition.equal(instrument.id, bar_type.instrument_id, "instrument.id", "bar_type.instrument_id")

        self._bar_type = bar_type
        self.price_precision = instrument.price_precision
        self.size_precision = instrument.size_precision
        self.initialized = False
        self.ts_last = 0
        self.count = 0

        self._partial_set = False
        self._last_close = None
        self._open = None
        self._high = None
        self._low = None
        self._close = None
        self.volume = Quantity.zero_c(precision=self.size_precision)

        self._log = Logger(name=type(self).__name__)

        self._ext_amt_accum = 0.0
        self._ext_amt_multiplier = 1.0
        if instrument is not None and hasattr(instrument, 'multiplier'):
            self._ext_amt_multiplier = (<Quantity>instrument.multiplier).as_double()


    def __repr__(self) -> str:
        return (
            f"{type(self).__name__}("
            f"{self._bar_type},"
            f"{self._open},"
            f"{self._high},"
            f"{self._low},"
            f"{self._close},"
            f"{self.volume})"
        )

    cpdef void set_partial(self, Bar partial_bar):
        """
        Set the initial values for a partially completed bar.
        """
        if self._partial_set:
            return  # Already updated

        self._open = partial_bar.open

        if self._high is None or partial_bar.high > self._high:
            self._high = partial_bar.high

        if self._low is None or partial_bar.low < self._low:
            self._low = partial_bar.low

        if self._close is None:
            self._close = partial_bar.close

        self.volume = partial_bar.volume

        if self.ts_last == 0:
            self.ts_last = partial_bar.ts_init
            self._log.debug(f"set_partial set ts_last to be {partial_bar.ts_init}")

        self._partial_set = True
        self.initialized = True

        # Restore amt accumulator from partial bar
        if partial_bar is not None:
            if not hasattr(partial_bar, 'amt'):
                raise ValueError(
                    f"Partial bar at {partial_bar.ts_event} is missing required 'amt' field. "
                    "Partial bars must have amt field when using extended bar builder."
                )
            self._ext_amt_accum = partial_bar.amt.as_double()


    cpdef void update(self, Price price, Quantity size, uint64_t ts_event):
        """
        Update the bar builder with a trade.
        """
        Condition.not_none(price, "price")
        Condition.not_none(size, "size")

        if ts_event < self.ts_last:
            return  # Not applicable

        if self._open is None:
            # Initialize builder
            self._open = price
            self._high = price
            self._low = price
            self.initialized = True
        elif price._mem.raw > self._high._mem.raw:
            self._high = price
        elif price._mem.raw < self._low._mem.raw:
            self._low = price

        self._close = price
        self.volume._mem.raw += size._mem.raw
        self.count += 1
        self.ts_last = ts_event
        if self.count == 1:
            self._log.debug(f"Trade tick set ts_last to {self.ts_last}")

        # Accumulate amt: price * size * multiplier
        self._ext_amt_accum += price.as_double() * size.as_double() * self._ext_amt_multiplier


    cpdef void update_bar(self, Bar bar, Quantity volume, uint64_t ts_init):
        """
        Update the bar builder with a child bar.
        """
        Condition.not_none(bar, "bar")

        if ts_init < self.ts_last:
            self._log.debug(f"Skipping out-of-order bar update: ts_init={pd.to_datetime(ts_init, unit='ns', utc=True)} < ts_last={pd.to_datetime(self.ts_last, unit='ns', utc=True)}")
            return  # Not applicable

        if self._open is None:
            # Initialize builder
            self._open = bar.open
            self._high = bar.high
            self._low = bar.low
            self.initialized = True
        else:
            if bar.high > self._high:
                self._high = bar.high

            if bar.low < self._low:
                self._low = bar.low

        self._close = bar.close
        self.volume._mem.raw += volume._mem.raw
        self.count += 1
        self.ts_last = ts_init
        self._log.debug(f"update_bar set self.ts_last to be {pd.to_datetime(ts_init, unit='ns', utc=True)}")


        # Accumulate amt from child bar - fail fast if missing
        if not hasattr(bar, 'amt'):
            raise ValueError(
                f"Child bar at {bar.ts_event} is missing required 'amt' field. "
                "All child bars must have amt field when building extended bars."
            )
        cdef double bar_amt_value = bar.amt.as_double()
        self._ext_amt_accum += bar_amt_value


    cpdef void reset(self):
        """
        Reset the bar builder.
        """
        self._open = None
        self._high = None
        self._low = None

        self.volume = Quantity.zero_c(precision=self.size_precision)
        self.count = 0

        self._ext_amt_accum = 0.0


    cpdef Bar build_now(self):
        """
        Return the aggregated bar and reset.
        """
        return self.build(self.ts_last, self.ts_last)

    cpdef Bar build(self, uint64_t ts_event, uint64_t ts_init):
        """
        Return the aggregated bar with the given closing timestamp, and reset.
        """
        if self._open is None:  # No tick was received
            self._open = self._last_close
            self._high = self._last_close
            self._low = self._last_close
            self._close = self._last_close

        self._low._mem.raw = min(self._close._mem.raw, self._low._mem.raw)
        self._high._mem.raw = max(self._close._mem.raw, self._high._mem.raw)

        cdef Bar bar = Bar(
            bar_type=self._bar_type,
            open=self._open,
            high=self._high,
            low=self._low,
            close=self._close,
            volume=Quantity(self.volume, self.size_precision),
            ts_event=ts_event,
            ts_init=ts_init,
        )

        # Write accumulated amt to bar
        bar.amt = Quantity(self._ext_amt_accum, self.size_precision)


        self._last_close = self._close
        self.reset()
        return bar
