// -------------------------------------------------------------------------------------------------
//  Copyright (C) 2015-2025 Nautech Systems Pty Ltd. All rights reserved.
//  https://nautechsystems.io
//
//  Licensed under the GNU Lesser General Public License Version 3.0 (the "License");
//  You may not use this file except in compliance with the License.
//  You may obtain a copy of the License at https://www.gnu.org/licenses/lgpl-3.0.en.html
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
// -------------------------------------------------------------------------------------------------

//! Build script for the `nautilus-model` crate.
//!
//! In addition to the common tasks performed by the other build scripts (header generation,
//! rerun-tracking, docs.rs early-exit) this script also toggles *high-precision* mode for the
//! generated bindings based on either:
//!
//! 1. The `HIGH_PRECISION` environment variable, **or**
//! 2. The compile-time `high-precision` cargo feature.
//!
//! When enabled the flag is forwarded to the Cython bindings via a `DEF HIGH_PRECISION` macro so
//! that the Python layer compiles in a compatible configuration.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct RawField {
    ident: String,
    #[serde(rename = "type")]
    field_type: String,
    doc: Option<String>,
    default: Option<String>,
    precision: Option<String>,
}

#[derive(Debug, Deserialize)]
struct RawFieldConfig {
    field: Vec<RawField>,
}

fn locate_extended_bar_config(manifest_dir: &Path) -> PathBuf {
    if let Ok(path) = env::var("EXTENDED_BAR_CONFIG_PATH") {
        return PathBuf::from(path);
    }

    if let Ok(workspace_dir) = env::var("CARGO_WORKSPACE_DIR") {
        let candidate = PathBuf::from(workspace_dir).join("configs/extended_bar_fields.toml");
        if candidate.exists() {
            return candidate;
        }
    }

    let mut current = manifest_dir.to_path_buf();
    loop {
        let candidate = current.join("configs/extended_bar_fields.toml");
        if candidate.exists() {
            return candidate;
        }
        if !current.pop() {
            break;
        }
    }

    panic!(
        "Extended bar configuration not found relative to {}. Set EXTENDED_BAR_CONFIG_PATH.",
        manifest_dir.display()
    );
}

fn read_extended_bar_config(config_path: &Path) -> RawFieldConfig {
    let config_raw = fs::read_to_string(config_path)
        .unwrap_or_else(|err| panic!("Failed to read {}: {err}", config_path.display()));

    toml::from_str(&config_raw)
        .unwrap_or_else(|err| panic!("Failed to parse {}: {err}", config_path.display()))
}

fn generate_extended_bar_spec() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let config_path = locate_extended_bar_config(&manifest_dir);

    // Re-run build script if config changes
    println!("cargo:rerun-if-changed={}", config_path.display());

    if !config_path.exists() {
        panic!(
            "Extended bar configuration not found: {} (create configs/extended_bar_fields.toml)",
            config_path.display()
        );
    }

    let config = read_extended_bar_config(&config_path);

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    let dest_path = out_dir.join("extended_bar_spec.rs");

    let mut contents = String::new();
    contents.push_str("// @generated by build.rs; do not edit manually\n");
    contents.push_str("use crate::data::extended_bar::{FieldSpec, FieldType};\n");
    contents.push_str("pub(crate) const EXTENDED_BAR_FIELD_SPECS: &[FieldSpec] = &[\n");

    for field in config.field {
        let variant = match field.field_type.as_str() {
            "quantity" => "FieldType::Quantity",
            "price" => "FieldType::Price",
            "u64" => "FieldType::U64",
            "bool" => "FieldType::Bool",
            other => panic!("Unsupported field type '{other}' for '{}'.", field.ident),
        };

        let doc = field.doc.unwrap_or_default();
        let default = field.default.unwrap_or_else(|| "0".to_string());
        let precision_expr = match field.precision.as_deref() {
            Some(value) => format!("Some(\"{}\")", escape_str(value)),
            None => "None".to_string(),
        };

        contents.push_str(&format!(
            "    FieldSpec {{ ident: \"{ident}\", field_type: {variant}, doc: \"{doc}\", default: \"{default}\", precision: {precision} }},\n",
            ident = escape_str(&field.ident),
            variant = variant,
            doc = escape_str(&doc),
            default = escape_str(&default),
            precision = precision_expr,
        ));
    }

    contents.push_str("];");

    fs::write(&dest_path, contents)
        .unwrap_or_else(|err| panic!("Failed to write {}: {err}", dest_path.display()));

    println!(
        "cargo:rustc-env=EXTENDED_BAR_SPEC_PATH={}",
        dest_path.canonicalize().unwrap_or(dest_path).display()
    );
}

fn escape_str(input: &str) -> String {
    input.chars().flat_map(|c| c.escape_default()).collect()
}

fn build_extended_bar_cython_params(config_path: &Path) -> Vec<(String, String)> {
    read_extended_bar_config(config_path)
        .field
        .into_iter()
        .map(|field| {
            let ty = match field.field_type.as_str() {
                "quantity" => "Quantity_t",
                "price" => "Price_t",
                "u64" => "uint64_t",
                "bool" => "bint",
                other => panic!(
                    "Unsupported extended bar field type '{other}' for '{}'.",
                    field.ident
                ),
            };

            (ty.to_string(), field.ident)
        })
        .collect()
}

fn rewrite_cython_bar_t_struct(contents: &str, params: &[(String, String)]) -> String {
    if params.is_empty() {
        return contents.to_string();
    }

    let mut lines: Vec<String> = contents.lines().map(|line| line.to_string()).collect();
    let had_trailing_newline = contents.ends_with('\n');
    let mut updated = false;

    // Find "cdef struct Bar_t:" and locate where to insert fields
    for index in 0..lines.len() {
        if !lines[index].trim().starts_with("cdef struct Bar_t:") {
            continue;
        }

        // Find the next struct or EOF to determine where Bar_t ends
        let mut end_idx = lines.len();
        for candidate in index + 1..lines.len() {
            let trimmed = lines[candidate].trim();
            if trimmed.starts_with("cdef struct") || trimmed.starts_with("cdef enum") || trimmed.starts_with("cdef class") {
                end_idx = candidate;
                break;
            }
        }

        // Find the last field in Bar_t (should be ts_init)
        let mut last_field_idx = index;
        for candidate in (index + 1..end_idx).rev() {
            if lines[candidate].contains("uint64_t ts_init") {
                last_field_idx = candidate;
                break;
            }
        }

        // Get indentation from existing fields
        let indent = "        ";

        // Insert extended fields after ts_init
        for (offset, (ty, name)) in params.iter().enumerate() {
            let comment = format!("{}# The bars {} (extended field).", indent, name);
            let field = format!("{}{} {};", indent, ty, name);

            lines.insert(last_field_idx + 1 + (offset * 2), field);
            lines.insert(last_field_idx + 1 + (offset * 2), comment);
        }

        updated = true;
        break;
    }

    if !updated {
        panic!("Failed to find `cdef struct Bar_t:` for extended bar rewrite in Cython pxd");
    }

    let mut output = lines.join("\n");
    if had_trailing_newline {
        output.push('\n');
    }
    output
}

fn rewrite_bar_new_signature(contents: &str, params: &[(String, String)]) -> String {
    if params.is_empty() {
        return contents.to_string();
    }

    let mut lines: Vec<String> = contents.lines().map(|line| line.to_string()).collect();
    let had_trailing_newline = contents.ends_with('\n');
    let mut updated = false;

    for index in 0..lines.len() {
        if !lines[index].contains("Bar_t bar_new(") {
            continue;
        }

        let mut closing_idx = None;
        for candidate in index + 1..lines.len() {
            if lines[candidate].trim_end().ends_with(");") {
                closing_idx = Some(candidate);
                break;
            }
        }

        let closing_idx = closing_idx
            .unwrap_or_else(|| panic!("Failed to locate end of bar_new signature in model.pxd"));

        let indent: String = lines[closing_idx]
            .chars()
            .take_while(|ch| ch.is_whitespace())
            .collect();

        let trimmed = lines[closing_idx].trim_end();
        let without_close = trimmed
            .strip_suffix(");")
            .unwrap_or_else(|| panic!("Expected bar_new signature to end with `);`"));
        let base = without_close
            .strip_prefix(&indent)
            .unwrap_or(without_close);

        lines[closing_idx] = format!("{indent}{base},");

        for (offset, (ty, ident)) in params.iter().enumerate() {
            let terminator = if offset + 1 == params.len() { ");" } else { "," };
            let entry = format!("{indent}{ty} {ident}{terminator}");
            lines.insert(closing_idx + 1 + offset, entry);
        }

        updated = true;
        break;
    }

    if !updated {
        panic!("Failed to find `bar_new` declaration for extended bar rewrite");
    }

    let mut output = lines.join("\n");
    if had_trailing_newline {
        output.push('\n');
    }
    output
}

fn build_extended_bar_header_params(config_path: &Path) -> Vec<(String, String)> {
    read_extended_bar_config(config_path)
        .field
        .into_iter()
        .map(|field| {
            let ty = match field.field_type.as_str() {
                "quantity" => "struct Quantity_t",
                "price" => "struct Price_t",
                "u64" => "uint64_t",
                "bool" => "uint8_t",
                other => panic!(
                    "Unsupported extended bar field type '{other}' for '{}'.",
                    field.ident
                ),
            };

            (ty.to_string(), field.ident)
        })
        .collect()
}

fn rewrite_bar_t_struct(contents: &str, params: &[(String, String)]) -> String {
    if params.is_empty() {
        return contents.to_string();
    }

    let mut lines: Vec<String> = contents.lines().map(|line| line.to_string()).collect();
    let had_trailing_newline = contents.ends_with('\n');
    let mut updated = false;

    // Find "typedef struct Bar_t {" and the closing "} Bar_t;"
    for index in 0..lines.len() {
        if !lines[index].contains("typedef struct Bar_t {") {
            continue;
        }

        // Find the closing brace
        let mut closing_idx = None;
        for candidate in index + 1..lines.len() {
            if lines[candidate].trim() == "} Bar_t;" {
                closing_idx = Some(candidate);
                break;
            }
        }

        let closing_idx = closing_idx
            .unwrap_or_else(|| panic!("Failed to locate end of Bar_t struct definition in model.h"));

        // Get indentation from existing fields (use same as ts_init)
        let indent = "    ";

        // Insert extended fields before the closing brace
        for (ty, name) in params.iter().rev() {
            let comment = format!("{}/**", indent);
            let doc = format!("{}* The bars {} (extended field).", indent, name);
            let end_comment = format!("{}*/", indent);
            // ty already contains "struct Quantity_t", so no need to add "struct" prefix
            let field = format!("{}{} {};", indent, ty, name);

            lines.insert(closing_idx, field);
            lines.insert(closing_idx, end_comment);
            lines.insert(closing_idx, doc);
            lines.insert(closing_idx, comment);
        }

        updated = true;
        break;
    }

    if !updated {
        panic!("Failed to find `typedef struct Bar_t` for extended bar struct rewrite");
    }

    let mut output = lines.join("\n");
    if had_trailing_newline {
        output.push('\n');
    }
    output
}

fn rewrite_bar_new_header_signature(contents: &str, params: &[(String, String)]) -> String {
    if params.is_empty() {
        return contents.to_string();
    }

    let mut lines: Vec<String> = contents.lines().map(|line| line.to_string()).collect();
    let had_trailing_newline = contents.ends_with('\n');
    let mut updated = false;

    for index in 0..lines.len() {
        if !lines[index].contains("struct Bar_t bar_new(") {
            continue;
        }

        let mut closing_idx = None;
        for candidate in index + 1..lines.len() {
            if lines[candidate].trim_end().ends_with(");") {
                closing_idx = Some(candidate);
                break;
            }
        }

        let closing_idx = closing_idx
            .unwrap_or_else(|| panic!("Failed to locate end of bar_new signature in model.h"));

        // The closing line is ");", we need to modify the line before it (last parameter)
        let last_param_line_idx = closing_idx - 1;

        // Extract indentation from the last parameter line
        let indent: String = lines[last_param_line_idx]
            .chars()
            .take_while(|ch| ch.is_whitespace())
            .collect();

        // Modify the closing line to remove ");" temporarily
        let closing_line = lines[closing_idx].clone();
        lines[closing_idx] = closing_line.replace(");", ",");

        // Insert extended field parameters after the current last parameter
        for (i, (ty, name)) in params.iter().enumerate() {
            let is_last = i == params.len() - 1;
            let line = if is_last {
                // Last extended parameter should end with ");", not ","
                format!("{}{} {})", indent, ty, name)
            } else {
                format!("{}{} {},", indent, ty, name)
            };
            lines.insert(closing_idx + 1 + i, line);
        }

        // Add ";" to the last line we inserted
        if let Some(last_line) = lines.get_mut(closing_idx + params.len()) {
            *last_line = format!("{};", last_line);
        }

        updated = true;
        break;
    }

    if !updated {
        panic!("Failed to find `bar_new` declaration for extended bar header rewrite");
    }

    let mut output = lines.join("\n");
    if had_trailing_newline {
        output.push('\n');
    }
    output
}

#[allow(clippy::expect_used)]
#[allow(unused_assignments)]
#[allow(unused_mut)]
fn main() {
    // Skip file generation if we're in the docs.rs environment
    if std::env::var("DOCS_RS").is_ok() {
        println!("cargo:warning=Running in docs.rs environment, skipping file generation");
        return;
    }

    generate_extended_bar_spec();

    // Ensure the build script runs on changes
    println!("cargo:rerun-if-env-changed=HIGH_PRECISION");
    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_HIGH_PRECISION");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=cbindgen.toml");
    println!("cargo:rerun-if-changed=cbindgen_cython.toml");
    println!("cargo:rerun-if-changed=../Cargo.toml");

    #[cfg(feature = "ffi")]
    if env::var("CARGO_FEATURE_FFI").is_ok() {
        extern crate cbindgen;
        use std::{
            fs::File,
            io::{Read, Write},
            path::PathBuf,
        };

        let crate_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));

        // Generate C headers
        let mut config_c = cbindgen::Config::from_file("cbindgen.toml")
            .expect("unable to find cbindgen.toml configuration file");

        // Check HIGH_PRECISION environment variable for C header too
        let high_precision_c = env::var("HIGH_PRECISION")
            .map(|v| v.to_lowercase() == "true" || v == "1")
            .unwrap_or_else(|_| {
                #[cfg(feature = "high-precision")]
                {
                    true
                }
                #[cfg(not(feature = "high-precision"))]
                {
                    false
                }
            });

        if high_precision_c && let Some(mut includes) = config_c.after_includes {
            includes.insert_str(0, "\n#define HIGH_PRECISION\n");
            config_c.after_includes = Some(includes);
        }

        let c_header_path = crate_dir.join("../../nautilus_trader/core/includes/model.h");
        cbindgen::generate_with_config(&crate_dir, config_c)
            .expect("unable to generate bindings")
            .write_to_file(&c_header_path);

        // Post-process C header to add extended bar fields to Bar_t struct and bar_new signature
        if cfg!(feature = "extended_bar") {
            let config_path = locate_extended_bar_config(&crate_dir);
            let header_params = build_extended_bar_header_params(&config_path);
            let header_contents = std::fs::read_to_string(&c_header_path)
                .expect("Failed to read generated C header");

            // Step 1: Add fields to Bar_t struct
            let with_struct = rewrite_bar_t_struct(&header_contents, &header_params);

            // Step 2: Add parameters to bar_new signature
            let rewritten_header = rewrite_bar_new_header_signature(&with_struct, &header_params);

            std::fs::write(&c_header_path, rewritten_header)
                .expect("Failed to write modified C header");
        }

        // Generate Cython definitions
        let mut config_cython = cbindgen::Config::from_file("cbindgen_cython.toml")
            .expect("unable to find cbindgen_cython.toml configuration file");

        // Check HIGH_PRECISION environment variable first, then fall back to feature flag
        let high_precision = env::var("HIGH_PRECISION")
            .map(|v| v.to_lowercase() == "true" || v == "1")
            .unwrap_or_else(|_| {
                #[cfg(feature = "high-precision")]
                {
                    true
                }
                #[cfg(not(feature = "high-precision"))]
                {
                    false
                }
            });

        let flag = if high_precision {
            Some("\nDEF HIGH_PRECISION = True  # or False".to_string())
        } else {
            Some("\nDEF HIGH_PRECISION = False  # or True".to_string())
        };

        // Activate Cython high-precision flag based on feature flags passed to Rust build
        config_cython.after_includes = flag;

        // Inject EXTENDED_BAR flag alongside HIGH_PRECISION
        let extended_bar = env::var("EXTENDED_BAR")
            .map(|v| v.to_lowercase() == "true" || v == "1")
            .unwrap_or_else(|_| {
                #[cfg(feature = "extended_bar")]
                {
                    true
                }
                #[cfg(not(feature = "extended_bar"))]
                {
                    false
                }
            });

        if extended_bar {
            if let Some(ref mut existing) = config_cython.after_includes {
                existing.push_str("\nDEF EXTENDED_BAR = True  # or False");
            }
        } else if let Some(ref mut existing) = config_cython.after_includes {
            existing.push_str("\nDEF EXTENDED_BAR = False  # or True");
        }

        let cython_path = crate_dir.join("../../nautilus_trader/core/rust/model.pxd");
        cbindgen::generate_with_config(&crate_dir, config_cython)
            .expect("unable to generate bindings")
            .write_to_file(cython_path.clone());

        // Open and read the file entirely
        let mut src = File::open(cython_path.clone()).expect("`File::open` failed");
        let mut data = String::new();
        src.read_to_string(&mut data)
            .expect("invalid UTF-8 in stream");

        // Run the replace operation in memory
        let mut data = data.replace("cdef enum", "cpdef enum");

        // Always add 128-bit typedefs for compatibility (they map to 64-bit on MSVC)
        {
            let lines: Vec<&str> = data.lines().collect();

            let mut output = String::new();
            let mut found_extern = false;

            for line in lines {
                output.push_str(line);
                output.push('\n');

                if !found_extern && line.trim().starts_with("cdef extern from") {
                    output.push_str("    ctypedef unsigned long long uint128_t\n");
                    output.push_str("    ctypedef long long int128_t\n");
                    found_extern = true;
                }
            }

            data = output;
        }

        if extended_bar {
            let config_path = locate_extended_bar_config(&crate_dir);
            let params = build_extended_bar_cython_params(&config_path);
            if !params.is_empty() {
                // Step 1: Add fields to Bar_t struct
                data = rewrite_cython_bar_t_struct(&data, &params);
                // Step 2: Add parameters to bar_new signature
                data = rewrite_bar_new_signature(&data, &params);
            }
        }

        // Recreate the file and dump the processed contents to it
        let mut dst = File::create(cython_path).expect("`File::create` failed");
        dst.write_all(data.as_bytes())
            .expect("I/O error on `dist.write`");
    }
}
